### ISSUE TITLE
Prompt 'cholera', 'what is cholera' are not giving a response

### ISSUE THREAD

**Issue by KanyantaM** [babakcode/flutter_gemini#5]
For some reason prompts 'cholera', and 'what is cholera' are not being given a response

**Comment by babakcode** [comment]
Hi @KanyantaM, I'm not a Google developer. I just made this package to connect to Gemini and all responses return from Gemini AI. IDK why this package can't respond to these concepts.

If you tested it from my web application, for testing some developers, sometimes the web application can't answer. You know, This is because Gemini has a limit on the number of responses it can generate per minute. Just try with your API key.

**Comment by KanyantaM** [comment]
I tried with my api key, on my device (android). And that's when I got the issue.
It responds on Bard so I assumed the issue could be with the package, because both are using Gemini pro. But I'll try to see what's causing it.
